spring:
  application:
    name: test-service

tracing:
  url: http://localhost:4318/v1/traces # Jaeger backend's endpoint

management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 means every TRACE and SPAN is reported to jaeger backend

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

